In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
x_train.shape

(4457,)

In [11]:
x_test.shape

(1115,)

In [12]:
type(x_train)

pandas.core.series.Series

In [15]:
# x_train[:4][1974]
x_train[:4]

1974    I had askd u a question some hours before. Its...
3782    Dear friends, sorry for the late information. ...
1607          Ok no prob... I'll come after lunch then...
70         Wah lucky man... Then can save money... Hee...
Name: Message, dtype: object

In [16]:
type(y_train)

pandas.core.series.Series

In [17]:
y_train[:4]

1974    0
3782    0
1607    0
70      0
Name: spam, dtype: int64

In [20]:
type(x_train.values)

numpy.ndarray

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<4457x7805 sparse matrix of type '<class 'numpy.int64'>'
	with 59372 stored elements in Compressed Sparse Row format>

In [22]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
x_train_cv.shape

(4457, 7805)

In [26]:
v.get_feature_names_out().shape

(7805,)

In [27]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [28]:
v.vocabulary_

{'had': 3337,
 'askd': 1100,
 'question': 5567,
 'some': 6344,
 'hours': 3562,
 'before': 1302,
 'its': 3811,
 'answer': 985,
 'dear': 2216,
 'friends': 3045,
 'sorry': 6378,
 'for': 2980,
 'the': 6868,
 'late': 4067,
 'information': 3720,
 'today': 6992,
 'is': 3792,
 'birthday': 1374,
 'of': 4931,
 'our': 5045,
 'loving': 4282,
 'ar': 1046,
 'praveesh': 5405,
 'more': 4629,
 'details': 2302,
 'log': 4224,
 'on': 4969,
 'to': 6985,
 'face': 2777,
 'book': 1440,
 'and': 962,
 'see': 6033,
 'his': 3486,
 'number': 4893,
 'lt': 4296,
 'gt': 3305,
 'dont': 2436,
 'miss': 4553,
 'delicious': 2257,
 'treat': 7082,
 'ok': 4953,
 'no': 4834,
 'prob': 5467,
 'll': 4209,
 'come': 1927,
 'after': 854,
 'lunch': 4307,
 'then': 6882,
 'wah': 7398,
 'lucky': 4301,
 'man': 4383,
 'can': 1647,
 'save': 5968,
 'money': 4613,
 'hee': 3433,
 'nothing': 4872,
 'much': 4679,
 'chillin': 1812,
 'at': 1123,
 'home': 3520,
 'any': 994,
 'super': 6659,
 'bowl': 1467,
 'plan': 5269,
 'what': 7528,
 'do': 2402,

In [29]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [30]:
v.get_feature_names_out()[3337]

'had'

In [33]:
x_train_np = x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
np.where(x_train_np[0]!=0)

(array([ 985, 1100, 1302, 3337, 3562, 3811, 5567, 6344], dtype=int64),)

In [35]:
x_train[:4][1974]

'I had askd u a question some hours before. Its answer'

In [37]:
x_train_np[0][985]

1

In [38]:
v.get_feature_names_out()[985]

'answer'

In [39]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [41]:
x_test_cv = v.transform(x_test)

In [42]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       967
           1       0.98      0.94      0.96       148

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [43]:
emails = [
    'Hey Mohan, can we get together to watch football game tomorrow?',
    "Upto 20% discount on parking, exclusive offer just for you. Don't miss this reward!"
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [44]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [45]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [47]:
y_pred = clf.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       967
           1       0.98      0.94      0.96       148

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

